name: Review

on: [pull_request]

jobs:
  build:

    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v1
    - name: bundle install
      run: |
        bundle install
        bundle exec fastlane review
